package sedaProfileGenerator;

public enum SAEColumn {
	SAE_ACCORDVERSEMENT, SAE_SERVEUR, TRANSFERIDPREFIX, TRANSFERIDVALUE, SAE_PROFILARCHIVAGE, TRANSFERRINGAGENCYID, TRANSFERRINGAGENCYNAME, TRANSFERRINGAGENCYDESC, ARCHIVALAGENCYID, ARCHIVALAGENCYNAME, ARCHIVALAGENCYDESC;
}
